# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bily5SX4f3j_8MhYMXLfUopn26gm59Pu
"""

import pandas as pd
baza={
    "FISH":["Rahmatov Nurbek","Nematullayev Rahmonjon","Rahmonaliyeva Nilufar"],
    "yoshi":["19","19","18"],
    "Manzili":["Jalaquduq tumani ","oltinko`l tumani ","Farg`ona"],
    "Jinsi":["erkak","erkak","ayol"],
     "Maktabi":["tatuff","tatuff", "maktabgacha talim"],
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=='erkak']
print(filtr)

filtr=db[(db['Jinsi']=='erkak')& (db['Maktabi']=='tatuff')&(db['yoshi']=='19')]
print(filtr)

filtr=db[db['Maktabi']=='maktabgacha talim']
print(filtr)